## This is an example on how to run OpenSearch and Dashboards including XDR plugins in a Docker environment.
## This is for demonstration and testing purposes only. Do not use this configuration in production environments.
services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=SecureP@ssword1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  xdr-plugins-sidecar:
    image: ghcr.io/kplrm/xdr-plugins:latest
    container_name: xdr-plugins
    volumes:
      - xdr-plugins:/plugins
    networks:
      - opensearch-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    volumes:
      - xdr-plugins:/xdr-plugins:ro
      - ./opensearch_dashboards.no-security.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node
      - xdr-plugins-sidecar
    command: >
      sh -c 'for p in /xdr-plugins/*.zip; do [ -e "$$p" ] || break; /usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin install --allow-root "file://$$p"; done; exec /usr/share/opensearch-dashboards/bin/opensearch-dashboards'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  opensearch-data:
  xdr-plugins:

networks:
  opensearch-net:
    driver: bridge
